### ISSUE TITLE
Desarrollo de Contratos Inteligentes

### ISSUE THREAD

**Issue by javiern-778** [SistemasTecTlaxiaco/infografia-lenguajes-de-programacion-javiern-778#1]
![Desarrollo de Contratos Inteligentes](https://user-images.githubusercontent.com/79878933/165670655-fe5476f9-61e4-4106-840a-1781ffb591ea.png)

**Comment by salathiel1999** [comment]
Calificación: 20 %

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
